/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peer2peer;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author carlo
 */
public class GUIClient extends javax.swing.JFrame {
    private HashMap<String, ArrayList<Mensaje>> mensajes;
    private ClientInterface cliente;
    private ClientImpl clienteIm;
    private ServerInterface servidor;
    
    private JPanel panelIzq;
    private JPanel panelDer;

    /**
     * Creates new form GUIClient
     */
    public GUIClient() {
        initComponents();
        this.mensajes = new HashMap<>();
        this.cliente = null;
        this.clienteIm = null;
        this.servidor = null;

        this.errorConexionLabel.setVisible(false);
        this.errorLoginLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        NombreText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JPasswordField();
        botonIniciarSesion = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PuertoText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        IpText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        errorConexionLabel = new javax.swing.JLabel();
        errorLoginLabel = new javax.swing.JLabel();
        botonIniciarSesion1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/round-account-button-with-user-inside_icon-icons.com_72596 (1).png"))); // NOI18N
        panelLogin.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));
        panelLogin.add(NombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 320, 30));
        panelLogin.add(PasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 320, 30));

        botonIniciarSesion.setBackground(new java.awt.Color(254, 254, 254));
        botonIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIniciarSesionMouseClicked(evt);
            }
        });
        botonIniciarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Iniciar Sesion");
        botonIniciarSesion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 120, 20));

        panelLogin.add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 220, 40));

        jLabel17.setText("Nombre");
        panelLogin.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel18.setText("Contraseña");
        panelLogin.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));
        panelLogin.add(PuertoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 320, 30));

        jLabel19.setText("Puerto");
        panelLogin.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        IpText.setText("localhost");
        panelLogin.add(IpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 320, 30));

        jLabel20.setText("IP");
        panelLogin.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        errorConexionLabel.setForeground(new java.awt.Color(168, 1, 1));
        errorConexionLabel.setText("No se ha podido conectar con el servidor");
        panelLogin.add(errorConexionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 300, 30));

        errorLoginLabel.setForeground(new java.awt.Color(168, 1, 1));
        errorLoginLabel.setText("El nombre de usuario o contraseña es incorrecto");
        panelLogin.add(errorLoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 320, 20));

        botonIniciarSesion1.setBackground(new java.awt.Color(254, 254, 254));
        botonIniciarSesion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIniciarSesion1MouseClicked(evt);
            }
        });
        botonIniciarSesion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("Crear cuenta");
        botonIniciarSesion1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 120, 20));

        panelLogin.add(botonIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 220, 40));

        getContentPane().add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarSesionMouseClicked
        try {
            // TODO add your handling code here:
            String hostname = this.IpText.getText();
            String puerto = this.PuertoText.getText();
            String nombre = this.NombreText.getText();
            String password = this.PasswordText.getText();

            String registryURL = "rmi://" + hostname + ":" + puerto + "/peer2peer";
            ServerInterface servidor = (ServerInterface) Naming.lookup(registryURL);
            ClientImpl clienteIm = new ClientImpl();
            ClientInterface cliente = clienteIm;
            clienteIm.setNombre(nombre);
            if (servidor.iniciarSesion(cliente, password)) {
                this.panelLogin.setVisible(false);
            }else{
                this.errorLoginLabel.setVisible(true);
                this.errorConexionLabel.setVisible(false);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(GUIClient.class.getName()).log(Level.SEVERE, null, ex);
            this.errorLoginLabel.setVisible(false);
            this.errorConexionLabel.setVisible(true);
        } catch (NotBoundException ex) {
            Logger.getLogger(GUIClient.class.getName()).log(Level.SEVERE, null, ex);
            this.errorLoginLabel.setVisible(false);
            this.errorConexionLabel.setVisible(true);
        } catch (MalformedURLException ex) {
            Logger.getLogger(GUIClient.class.getName()).log(Level.SEVERE, null, ex);
            this.errorLoginLabel.setVisible(false);
            this.errorConexionLabel.setVisible(true);
        }
    }//GEN-LAST:event_botonIniciarSesionMouseClicked

    private void botonIniciarSesion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarSesion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIniciarSesion1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIClient().setVisible(true);
            }
        });
    }
    public void anadirMensaje(String amigo, String emisor, String mensaje){
        if(this.mensajes.get(amigo).size()==10){
            ArrayList<Mensaje> aux = new ArrayList<>();
            for(int i =1; i<10; i++){
                mensajes.get(amigo).set(i-1, mensajes.get(amigo).get(i));
            }
            mensajes.get(amigo).set(9, new Mensaje(emisor, mensaje));
            
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IpText;
    private javax.swing.JTextField NombreText;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JTextField PuertoText;
    private javax.swing.JPanel botonIniciarSesion;
    private javax.swing.JPanel botonIniciarSesion1;
    private javax.swing.JLabel errorConexionLabel;
    private javax.swing.JLabel errorLoginLabel;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel panelLogin;
    // End of variables declaration//GEN-END:variables
}


