/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peer2peer;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author raquel
 */
public class panelNotificaciones extends javax.swing.JPanel {

    /**
     * Creates new form panelNotificaciones
     */
    public panelNotificaciones() {
        initComponents();
        tablaNotificaciones.setDefaultRenderer(String.class, new RowRendererNotificaciones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotificaciones = new javax.swing.JTable();
        botonLeido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(204, 147, 78));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-alarma-filled-18.png"))); // NOI18N
        jLabel1.setText("Notificaciones");
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, -1));

        add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 360, 50));

        jScrollPane1.setBackground(new java.awt.Color(254, 254, 254));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tablaNotificaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablaNotificaciones.setModel(new ModeloTablaUsuarios());
        tablaNotificaciones.setGridColor(new java.awt.Color(254, 254, 254));
        tablaNotificaciones.setTableHeader(null);
        jScrollPane1.setViewportView(tablaNotificaciones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 300));

        botonLeido.setBackground(new java.awt.Color(144, 144, 144));
        botonLeido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLeido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLeidoMouseClicked(evt);
            }
        });
        botonLeido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Borrar notificacion");
        botonLeido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 140, 30));

        add(botonLeido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void botonLeidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLeidoMouseClicked
        // TODO add your handling code here:
        ModeloTablaUsuarios tt;
        tt = (ModeloTablaUsuarios) tablaNotificaciones.getModel();
        tt.removeFila(tablaNotificaciones.getSelectedRow());

//        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
//        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
//        tablaNotificaciones.setDefaultRenderer(String.class, centerRenderer);
    }//GEN-LAST:event_botonLeidoMouseClicked

    public void addNotificacion(String notificacion) {
        ModeloTablaUsuarios tt;
        tt = (ModeloTablaUsuarios) tablaNotificaciones.getModel();
        tt.addFila(notificacion);
    }
    
    public void vaciar(){
        ModeloTablaUsuarios tt;
        tt = (ModeloTablaUsuarios) tablaNotificaciones.getModel();
        tt.setFilas(new ArrayList<>());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonLeido;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaNotificaciones;
    // End of variables declaration//GEN-END:variables
}
