/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peer2peer;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author raquel
 */
public class panelNotificaciones extends javax.swing.JPanel {

    /**
     * Creates new form panelNotificaciones
     */
    public panelNotificaciones() {
        initComponents();
        tablaNotificaciones.setDefaultRenderer(String.class, new RowRendererNotificaciones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotificaciones = new javax.swing.JTable();
        botonVaciar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonLeido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(204, 147, 78));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-alarma-filled-18.png"))); // NOI18N
        jLabel1.setText("Notificaciones");
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, -1));

        add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 360, 50));

        jScrollPane1.setBackground(new java.awt.Color(254, 254, 254));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tablaNotificaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablaNotificaciones.setModel(new ModeloTablaUsuarios());
        tablaNotificaciones.setGridColor(new java.awt.Color(254, 254, 254));
        tablaNotificaciones.setTableHeader(null);
        jScrollPane1.setViewportView(tablaNotificaciones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 340));

        botonVaciar.setBackground(new java.awt.Color(144, 144, 144));
        botonVaciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVaciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVaciarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonVaciarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonVaciarMouseEntered(evt);
            }
        });
        botonVaciar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(254, 254, 254));
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-basura-18.png"))); // NOI18N
        jLabel2.setText("Vaciar");
        botonVaciar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        add(botonVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 80, 30));

        botonLeido.setBackground(new java.awt.Color(144, 144, 144));
        botonLeido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLeido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLeidoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonLeidoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonLeidoMouseEntered(evt);
            }
        });
        botonLeido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(254, 254, 254));
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Borrar notificacion");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLeido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 30));

        add(botonLeido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void botonVaciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVaciarMouseClicked
        // TODO add your handling code here:
        this.vaciar();
//        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
//        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
//        tablaNotificaciones.setDefaultRenderer(String.class, centerRenderer);
    }//GEN-LAST:event_botonVaciarMouseClicked

    private void botonLeidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLeidoMouseClicked
        // TODO add your handling code here:
        ModeloTablaUsuarios tt;
        tt = (ModeloTablaUsuarios) tablaNotificaciones.getModel();
        tt.removeFila(tablaNotificaciones.getSelectedRow());
    }//GEN-LAST:event_botonLeidoMouseClicked

    private void botonVaciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVaciarMouseEntered
        // TODO add your handling code here:
        botonVaciar.setBackground(new Color(162,162,162));
    }//GEN-LAST:event_botonVaciarMouseEntered

    private void botonLeidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLeidoMouseEntered
        // TODO add your handling code here:
        botonLeido.setBackground(new Color(162,162,162));
    }//GEN-LAST:event_botonLeidoMouseEntered

    private void botonLeidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLeidoMouseExited
        // TODO add your handling code here:
        botonLeido.setBackground(new Color(144,144,144));
    }//GEN-LAST:event_botonLeidoMouseExited

    private void botonVaciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVaciarMouseExited
        // TODO add your handling code here:
        botonVaciar.setBackground(new Color(144,144,144));
    }//GEN-LAST:event_botonVaciarMouseExited

    public void addNotificacion(String notificacion) {
        ModeloTablaUsuarios tt;
        tt = (ModeloTablaUsuarios) tablaNotificaciones.getModel();
        tt.addFila(notificacion);
    }
    
    public void vaciar(){
        ModeloTablaUsuarios tt;
        tt = (ModeloTablaUsuarios) tablaNotificaciones.getModel();
        tt.setFilas(new ArrayList<>());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonLeido;
    private javax.swing.JPanel botonVaciar;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaNotificaciones;
    // End of variables declaration//GEN-END:variables
}
