/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peer2peer;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author carlo
 */
public class panelPeticiones extends javax.swing.JPanel {
    GUIClient parent;
    /**
     * Creates new form panelPeticiones
     */
    public panelPeticiones(GUIClient parent, ArrayList<String> peticiones) {
        initComponents();
        this.mensajeAcetarPeticion.setVisible(false);
        this.mensajeRechazarPeticion.setVisible(false);
        this.parent = parent;
        ModeloTablaUsuarios tt;
        tt = (ModeloTablaUsuarios) tablaPeticiones.getModel();
        tt.setFilas(peticiones);
        

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        Font fuente = new Font("SansSerif", Font.ITALIC, 25);
        headerRenderer.setFont(fuente);
        headerRenderer.setBackground(new Color(23,118,137));
        headerRenderer.setForeground(Color.WHITE);
        this.tablaPeticiones.getColumnModel().getColumn(0).setHeaderRenderer(headerRenderer);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPeticiones = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        botonRechazarPeticion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonAceptarPeticion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mensajeAcetarPeticion = new javax.swing.JLabel();
        mensajeRechazarPeticion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(680, 450));
        setMinimumSize(new java.awt.Dimension(680, 450));
        setPreferredSize(new java.awt.Dimension(680, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(254, 254, 254));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tablaPeticiones.setModel(new ModeloTablaUsuarios());
        jScrollPane2.setViewportView(tablaPeticiones);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 500, 240));

        jPanel1.setBackground(new java.awt.Color(234, 168, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Peticiones de amistad pendientes");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 460, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 720, 50));

        botonRechazarPeticion.setBackground(new java.awt.Color(23, 118, 137));
        botonRechazarPeticion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonRechazarPeticion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRechazarPeticionMouseClicked(evt);
            }
        });
        botonRechazarPeticion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Rechazar petición");
        botonRechazarPeticion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 40));

        add(botonRechazarPeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 200, 40));

        botonAceptarPeticion.setBackground(new java.awt.Color(23, 118, 137));
        botonAceptarPeticion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonAceptarPeticion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAceptarPeticionMouseClicked(evt);
            }
        });
        botonAceptarPeticion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aceptar peticion");
        botonAceptarPeticion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 40));

        add(botonAceptarPeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 190, 40));

        mensajeAcetarPeticion.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        mensajeAcetarPeticion.setForeground(new java.awt.Color(12, 87, 0));
        mensajeAcetarPeticion.setText("Has agregado un nuevo amigo");
        add(mensajeAcetarPeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        mensajeRechazarPeticion.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        mensajeRechazarPeticion.setForeground(new java.awt.Color(135, 1, 1));
        mensajeRechazarPeticion.setText("Has rechazado la peticion");
        add(mensajeRechazarPeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRechazarPeticionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRechazarPeticionMouseClicked
        ModeloTablaUsuarios tt;
        tt = (ModeloTablaUsuarios) tablaPeticiones.getModel();
        this.mensajeRechazarPeticion.setText("Has rechazado la peticion de amistad de " + tt.getFila(tablaPeticiones.getSelectedRow()));
        tt.setFilas(parent.rechazarPeticion(tt.getFila(tablaPeticiones.getSelectedRow())));
        this.mensajeRechazarPeticion.setVisible(true);
        this.mensajeAcetarPeticion.setVisible(false);
    }//GEN-LAST:event_botonRechazarPeticionMouseClicked

    private void botonAceptarPeticionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarPeticionMouseClicked
        // TODO add your handling code here:
        ModeloTablaUsuarios tt;
        tt = (ModeloTablaUsuarios) tablaPeticiones.getModel();
        this.mensajeAcetarPeticion.setText("Ahora tú y " + tt.getFila(tablaPeticiones.getSelectedRow()) + " sois amigos");
        tt.setFilas(parent.aceptarPeticion(tt.getFila(tablaPeticiones.getSelectedRow())));
        this.mensajeAcetarPeticion.setVisible(true);
        this.mensajeRechazarPeticion.setVisible(false);
    }//GEN-LAST:event_botonAceptarPeticionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonAceptarPeticion;
    private javax.swing.JPanel botonRechazarPeticion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mensajeAcetarPeticion;
    private javax.swing.JLabel mensajeRechazarPeticion;
    private javax.swing.JTable tablaPeticiones;
    // End of variables declaration//GEN-END:variables
}
