/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peer2peer;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author carlo
 */
public class panelChats extends javax.swing.JPanel {

    GUIClient parent;
    String chatActivo;
    HashMap<String, ArrayList<Mensaje>> mensajes;

    /**
     * Creates new form panelChats
     */
    public panelChats(GUIClient parent, HashMap<String, ArrayList<Mensaje>> mensajes) {
        initComponents();
        this.parent = parent;
        this.mensajes = mensajes;
        ModeloTablaUsuarios tabla = new ModeloTablaUsuarios();
         DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        Font fuente = new Font("SansSerif", Font.PLAIN, 14);
        
        this.tablaChats.setTableHeader(null);;
        this.tablaChats.setFont(fuente);
        this.tablaChats.setRowHeight(25);
        tablaChats.setModel(tabla);
        this.panelConver.setVisible(false);
        try {
            tabla.setFilas(new ArrayList<>(Arrays.asList(parent.getClienteIm().getAmigos())));
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConver = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nombreAmigoChat = new javax.swing.JLabel();
        enLinea = new javax.swing.JLabel();
        desconectado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mensaje0 = new javax.swing.JLabel();
        mensaje9 = new javax.swing.JLabel();
        mensaje8 = new javax.swing.JLabel();
        mensaje7 = new javax.swing.JLabel();
        mensaje6 = new javax.swing.JLabel();
        mensaje5 = new javax.swing.JLabel();
        mensaje4 = new javax.swing.JLabel();
        mensaje3 = new javax.swing.JLabel();
        mensaje2 = new javax.swing.JLabel();
        mensaje1 = new javax.swing.JLabel();
        enviarMensaje = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textoMensaje = new javax.swing.JTextField();
        panelAmigos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaChats = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(680, 450));
        setPreferredSize(new java.awt.Dimension(680, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelConver.setBackground(new java.awt.Color(255, 255, 255));
        panelConver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(80, 140, 31));
        jPanel1.setFont(jPanel1.getFont());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreAmigoChat.setBackground(new java.awt.Color(255, 255, 255));
        nombreAmigoChat.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        nombreAmigoChat.setForeground(new java.awt.Color(255, 255, 255));
        nombreAmigoChat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreAmigoChat.setText("NOMBRE DEL AMIGO");
        jPanel1.add(nombreAmigoChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 210, 40));

        enLinea.setForeground(new java.awt.Color(255, 255, 255));
        enLinea.setText("(EN LÍNEA)");
        jPanel1.add(enLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 70, 40));

        desconectado.setForeground(new java.awt.Color(255, 255, 255));
        desconectado.setText("DESCONECTADO");
        jPanel1.add(desconectado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuario-de-género-neutro-36.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        panelConver.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 40));

        mensaje0.setBackground(new java.awt.Color(102, 102, 102));
        mensaje0.setText("jLabel1");
        panelConver.add(mensaje0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 400, 35));

        mensaje9.setBackground(new java.awt.Color(102, 102, 102));
        mensaje9.setText("jLabel1");
        panelConver.add(mensaje9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 400, 35));

        mensaje8.setBackground(new java.awt.Color(102, 102, 102));
        mensaje8.setText("jLabel1");
        panelConver.add(mensaje8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 400, 35));

        mensaje7.setBackground(new java.awt.Color(102, 102, 102));
        mensaje7.setText("jLabel1");
        panelConver.add(mensaje7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 400, 35));

        mensaje6.setBackground(new java.awt.Color(102, 102, 102));
        mensaje6.setText("jLabel1");
        panelConver.add(mensaje6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 400, 35));

        mensaje5.setBackground(new java.awt.Color(102, 102, 102));
        mensaje5.setText("jLabel1");
        panelConver.add(mensaje5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 400, 35));

        mensaje4.setBackground(new java.awt.Color(102, 102, 102));
        mensaje4.setText("jLabel1");
        panelConver.add(mensaje4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 400, 35));

        mensaje3.setBackground(new java.awt.Color(102, 102, 102));
        mensaje3.setText("jLabel1");
        panelConver.add(mensaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 400, 35));

        mensaje2.setBackground(new java.awt.Color(102, 102, 102));
        mensaje2.setText("jLabel1");
        panelConver.add(mensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 400, 35));

        mensaje1.setBackground(new java.awt.Color(102, 102, 102));
        mensaje1.setText("jLabel1");
        panelConver.add(mensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 400, 35));

        enviarMensaje.setBackground(new java.awt.Color(255, 255, 255));
        enviarMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarMensajeMouseClicked(evt);
            }
        });
        enviarMensaje.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-enviado-34.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        enviarMensaje.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        panelConver.add(enviarMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 40, 30));

        textoMensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoMensajeKeyPressed(evt);
            }
        });
        panelConver.add(textoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 400, 30));

        add(panelConver, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 440, 450));

        panelAmigos.setBackground(new java.awt.Color(255, 255, 255));
        panelAmigos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tablaChats.setModel(new ModeloTablaUsuarios());
        tablaChats.setGridColor(new java.awt.Color(254, 254, 254));
        tablaChats.setSelectionBackground(new java.awt.Color(142, 193, 91));
        tablaChats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaChatsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaChats);

        panelAmigos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 400));

        jPanel2.setBackground(new java.awt.Color(234, 168, 87));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Amigos");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 40));

        panelAmigos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 40));

        add(panelAmigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaChatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaChatsMouseClicked
        // TODO add your handling code here:
        ModeloTablaUsuarios m = (ModeloTablaUsuarios) tablaChats.getModel();
        this.panelConver.setVisible(true);
        try {
            String receptor = m.getFila(tablaChats.getSelectedRow());
            nombreAmigoChat.setText(receptor);
            if (parent.getClienteIm().getAmigosConectados().get(receptor) == null) {
                enLinea.setVisible(false);
                desconectado.setVisible(true);
            }else{
                enLinea.setVisible(true);
                desconectado.setVisible(false);
            }
            escribirMensajes(receptor);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tablaChatsMouseClicked

    private void enviarMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarMensajeMouseClicked
        // TODO add your handling code here:
        if (parent.getClienteIm().getAmigosConectados().get(nombreAmigoChat.getText()) == null) {
                enLinea.setVisible(false);
                desconectado.setVisible(true);
            }else{
                enLinea.setVisible(true);
                desconectado.setVisible(false);
            }
        if (parent.getClienteIm().getAmigosConectados().get(nombreAmigoChat.getText()) == null || textoMensaje.getText() == null || textoMensaje.getText() == "") {
            return;
        } else {
            try {
                parent.getClienteIm().getAmigosConectados().get(nombreAmigoChat.getText()).recibirMensaje(textoMensaje.getText(), parent.getClienteIm().getNombre());
                parent.anadirMensaje(nombreAmigoChat.getText(), parent.getClienteIm().getNombre(), textoMensaje.getText());
                escribirMensajes(nombreAmigoChat.getText());
                textoMensaje.setText("");
            } catch (RemoteException ex) {
                Logger.getLogger(panelChats.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_enviarMensajeMouseClicked

    private void textoMensajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoMensajeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (parent.getClienteIm().getAmigosConectados().get(nombreAmigoChat.getText()) == null || textoMensaje.getText() == null || textoMensaje.getText() == "") {
                return;
            } else {
                try {
                    parent.getClienteIm().getAmigosConectados().get(nombreAmigoChat.getText()).recibirMensaje(textoMensaje.getText(), parent.getClienteIm().getNombre());
                    parent.anadirMensaje(nombreAmigoChat.getText(), parent.getClienteIm().getNombre(), textoMensaje.getText());
                    escribirMensajes(nombreAmigoChat.getText());
                    textoMensaje.setText("");
                } catch (RemoteException ex) {
                    Logger.getLogger(panelChats.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_textoMensajeKeyPressed
    public void escribirMensajes(String receptor) {

        ArrayList<Mensaje> mensajesChat = mensajes.get(receptor);
        switch (mensajesChat.size()) {
            case 10:
                mensaje0.setText(mensajesChat.get(9).getMensaje());
                if (mensajesChat.get(9).getEmisor().equals(receptor)) {
                    mensaje0.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje0.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje1.setText(mensajesChat.get(8).getMensaje());
                if (mensajesChat.get(8).getEmisor().equals(receptor)) {
                    mensaje1.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje1.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje2.setText(mensajesChat.get(7).getMensaje());
                if (mensajesChat.get(7).getEmisor().equals(receptor)) {
                    mensaje2.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje2.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje3.setText(mensajesChat.get(6).getMensaje());
                if (mensajesChat.get(6).getEmisor().equals(receptor)) {
                    mensaje3.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje3.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje4.setText(mensajesChat.get(5).getMensaje());
                if (mensajesChat.get(5).getEmisor().equals(receptor)) {
                    mensaje4.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje4.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje5.setText(mensajesChat.get(4).getMensaje());
                if (mensajesChat.get(4).getEmisor().equals(receptor)) {
                    mensaje5.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje5.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje6.setText(mensajesChat.get(3).getMensaje());
                if (mensajesChat.get(3).getEmisor().equals(receptor)) {
                    mensaje6.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje6.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje7.setText(mensajesChat.get(2).getMensaje());
                if (mensajesChat.get(2).getEmisor().equals(receptor)) {
                    mensaje7.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje7.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje8.setText(mensajesChat.get(1).getMensaje());
                if (mensajesChat.get(1).getEmisor().equals(receptor)) {
                    mensaje8.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje8.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje9.setText(mensajesChat.get(0).getMensaje());
                if (mensajesChat.get(0).getEmisor().equals(receptor)) {
                    mensaje9.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje9.setHorizontalAlignment(SwingConstants.RIGHT);
                }
                break;
            case 9:
                mensaje0.setText(mensajesChat.get(8).getMensaje());
                if (mensajesChat.get(8).getEmisor().equals(receptor)) {
                    mensaje0.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje0.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje1.setText(mensajesChat.get(7).getMensaje());
                if (mensajesChat.get(7).getEmisor().equals(receptor)) {
                    mensaje1.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje1.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje2.setText(mensajesChat.get(6).getMensaje());
                if (mensajesChat.get(6).getEmisor().equals(receptor)) {
                    mensaje2.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje2.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje3.setText(mensajesChat.get(5).getMensaje());
                if (mensajesChat.get(5).getEmisor().equals(receptor)) {
                    mensaje3.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje3.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje4.setText(mensajesChat.get(4).getMensaje());
                if (mensajesChat.get(4).getEmisor().equals(receptor)) {
                    mensaje4.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje4.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje5.setText(mensajesChat.get(3).getMensaje());
                if (mensajesChat.get(3).getEmisor().equals(receptor)) {
                    mensaje5.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje5.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje6.setText(mensajesChat.get(2).getMensaje());
                if (mensajesChat.get(2).getEmisor().equals(receptor)) {
                    mensaje6.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje6.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje7.setText(mensajesChat.get(1).getMensaje());
                if (mensajesChat.get(1).getEmisor().equals(receptor)) {
                    mensaje7.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje7.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje8.setText(mensajesChat.get(0).getMensaje());
                if (mensajesChat.get(0).getEmisor().equals(receptor)) {
                    mensaje8.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje8.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje9.setText("");
                break;
            case 8:
                mensaje0.setText(mensajesChat.get(7).getMensaje());
                if (mensajesChat.get(7).getEmisor().equals(receptor)) {
                    mensaje0.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje0.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje1.setText(mensajesChat.get(6).getMensaje());
                if (mensajesChat.get(6).getEmisor().equals(receptor)) {
                    mensaje1.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje1.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje2.setText(mensajesChat.get(5).getMensaje());
                if (mensajesChat.get(5).getEmisor().equals(receptor)) {
                    mensaje2.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje2.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje3.setText(mensajesChat.get(4).getMensaje());
                if (mensajesChat.get(4).getEmisor().equals(receptor)) {
                    mensaje3.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje3.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje4.setText(mensajesChat.get(3).getMensaje());
                if (mensajesChat.get(3).getEmisor().equals(receptor)) {
                    mensaje4.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje4.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje5.setText(mensajesChat.get(2).getMensaje());
                if (mensajesChat.get(2).getEmisor().equals(receptor)) {
                    mensaje5.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje5.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje6.setText(mensajesChat.get(1).getMensaje());
                if (mensajesChat.get(1).getEmisor().equals(receptor)) {
                    mensaje6.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje6.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje7.setText(mensajesChat.get(0).getMensaje());
                if (mensajesChat.get(0).getEmisor().equals(receptor)) {
                    mensaje7.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje7.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje8.setText("");
                mensaje9.setText("");
                break;
            case 7:
                mensaje0.setText(mensajesChat.get(6).getMensaje());
                if (mensajesChat.get(6).getEmisor().equals(receptor)) {
                    mensaje0.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje0.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje1.setText(mensajesChat.get(5).getMensaje());
                if (mensajesChat.get(5).getEmisor().equals(receptor)) {
                    mensaje1.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje1.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje2.setText(mensajesChat.get(4).getMensaje());
                if (mensajesChat.get(4).getEmisor().equals(receptor)) {
                    mensaje2.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje2.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje3.setText(mensajesChat.get(3).getMensaje());
                if (mensajesChat.get(3).getEmisor().equals(receptor)) {
                    mensaje3.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje3.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje4.setText(mensajesChat.get(2).getMensaje());
                if (mensajesChat.get(2).getEmisor().equals(receptor)) {
                    mensaje4.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje4.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje5.setText(mensajesChat.get(1).getMensaje());
                if (mensajesChat.get(1).getEmisor().equals(receptor)) {
                    mensaje5.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje5.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje6.setText(mensajesChat.get(0).getMensaje());
                if (mensajesChat.get(0).getEmisor().equals(receptor)) {
                    mensaje6.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje6.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje7.setText("");
                mensaje8.setText("");
                mensaje9.setText("");
                break;
            case 6:
                mensaje0.setText(mensajesChat.get(5).getMensaje());
                if (mensajesChat.get(5).getEmisor().equals(receptor)) {
                    mensaje0.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje0.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje1.setText(mensajesChat.get(4).getMensaje());
                if (mensajesChat.get(4).getEmisor().equals(receptor)) {
                    mensaje1.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje1.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje2.setText(mensajesChat.get(3).getMensaje());
                if (mensajesChat.get(3).getEmisor().equals(receptor)) {
                    mensaje2.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje2.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje3.setText(mensajesChat.get(2).getMensaje());
                if (mensajesChat.get(2).getEmisor().equals(receptor)) {
                    mensaje3.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje3.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje4.setText(mensajesChat.get(1).getMensaje());
                if (mensajesChat.get(1).getEmisor().equals(receptor)) {
                    mensaje4.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje4.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje5.setText(mensajesChat.get(0).getMensaje());
                if (mensajesChat.get(0).getEmisor().equals(receptor)) {
                    mensaje5.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje5.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje6.setText("");
                mensaje7.setText("");
                mensaje8.setText("");
                mensaje9.setText("");
                break;
            case 5:
                mensaje0.setText(mensajesChat.get(4).getMensaje());
                if (mensajesChat.get(4).getEmisor().equals(receptor)) {
                    mensaje0.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje0.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje1.setText(mensajesChat.get(3).getMensaje());
                if (mensajesChat.get(3).getEmisor().equals(receptor)) {
                    mensaje1.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje1.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje2.setText(mensajesChat.get(2).getMensaje());
                if (mensajesChat.get(2).getEmisor().equals(receptor)) {
                    mensaje2.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje2.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje3.setText(mensajesChat.get(1).getMensaje());
                if (mensajesChat.get(1).getEmisor().equals(receptor)) {
                    mensaje3.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje3.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje4.setText(mensajesChat.get(0).getMensaje());
                if (mensajesChat.get(0).getEmisor().equals(receptor)) {
                    mensaje4.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje4.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje5.setText("");
                mensaje6.setText("");
                mensaje7.setText("");
                mensaje8.setText("");
                mensaje9.setText("");
                break;
            case 4:
                mensaje0.setText(mensajesChat.get(3).getMensaje());
                if (mensajesChat.get(3).getEmisor().equals(receptor)) {
                    mensaje0.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje0.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje1.setText(mensajesChat.get(2).getMensaje());
                if (mensajesChat.get(2).getEmisor().equals(receptor)) {
                    mensaje1.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje1.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje2.setText(mensajesChat.get(1).getMensaje());
                if (mensajesChat.get(1).getEmisor().equals(receptor)) {
                    mensaje2.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje2.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje3.setText(mensajesChat.get(0).getMensaje());
                if (mensajesChat.get(0).getEmisor().equals(receptor)) {
                    mensaje3.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje3.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje4.setText("");
                mensaje5.setText("");
                mensaje6.setText("");
                mensaje7.setText("");
                mensaje8.setText("");
                mensaje9.setText("");
                break;
            case 3:
                mensaje0.setText(mensajesChat.get(2).getMensaje());
                if (mensajesChat.get(2).getEmisor().equals(receptor)) {
                    mensaje0.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje0.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje1.setText(mensajesChat.get(1).getMensaje());
                if (mensajesChat.get(1).getEmisor().equals(receptor)) {
                    mensaje1.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje1.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje2.setText(mensajesChat.get(0).getMensaje());
                if (mensajesChat.get(0).getEmisor().equals(receptor)) {
                    mensaje2.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje2.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje3.setText("");
                mensaje4.setText("");
                mensaje5.setText("");
                mensaje6.setText("");
                mensaje7.setText("");
                mensaje8.setText("");
                mensaje9.setText("");
                break;
            case 2:
                mensaje0.setText(mensajesChat.get(1).getMensaje());
                if (mensajesChat.get(1).getEmisor().equals(receptor)) {
                    mensaje0.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje0.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje1.setText(mensajesChat.get(0).getMensaje());
                if (mensajesChat.get(0).getEmisor().equals(receptor)) {
                    mensaje1.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje1.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje2.setText("");
                mensaje3.setText("");
                mensaje4.setText("");
                mensaje5.setText("");
                mensaje6.setText("");
                mensaje7.setText("");
                mensaje8.setText("");
                mensaje9.setText("");
                break;
            case 1:
                mensaje0.setText(mensajesChat.get(0).getMensaje());
                if (mensajesChat.get(0).getEmisor().equals(receptor)) {
                    mensaje0.setHorizontalAlignment(SwingConstants.LEFT);
                } else {
                    mensaje0.setHorizontalAlignment(SwingConstants.RIGHT);
                }

                mensaje1.setText("");
                mensaje2.setText("");
                mensaje3.setText("");
                mensaje4.setText("");
                mensaje5.setText("");
                mensaje6.setText("");
                mensaje7.setText("");
                mensaje8.setText("");
                mensaje9.setText("");
                break;
            case 0:
                mensaje0.setText("");
                mensaje1.setText("");
                mensaje2.setText("");
                mensaje3.setText("");
                mensaje4.setText("");
                mensaje5.setText("");
                mensaje6.setText("");
                mensaje7.setText("");
                mensaje8.setText("");
                mensaje9.setText("");
                break;

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel desconectado;
    private javax.swing.JLabel enLinea;
    private javax.swing.JPanel enviarMensaje;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mensaje0;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JLabel mensaje3;
    private javax.swing.JLabel mensaje4;
    private javax.swing.JLabel mensaje5;
    private javax.swing.JLabel mensaje6;
    private javax.swing.JLabel mensaje7;
    private javax.swing.JLabel mensaje8;
    private javax.swing.JLabel mensaje9;
    private javax.swing.JLabel nombreAmigoChat;
    private javax.swing.JPanel panelAmigos;
    private javax.swing.JPanel panelConver;
    private javax.swing.JTable tablaChats;
    private javax.swing.JTextField textoMensaje;
    // End of variables declaration//GEN-END:variables
}
