/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peer2peer;

import java.util.*;
/**
 *
 * @author carlo
 */
public class panelBuscar extends javax.swing.JPanel {

    GUIClient parent;
    String usuario;

    /**
     * Creates new form panelDer
     */
    
    public panelBuscar(){
        initComponents();
    }
    public panelBuscar(GUIClient parent, String usuario) {
        initComponents();
        this.parent = parent;
        this.usuario = usuario;
        this.peticionCorrecta.setVisible(false);
        this.peticionIncorrecta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoBuscar = new javax.swing.JTextField();
        buscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBuscar = new javax.swing.JTable();
        enviarPeticion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        peticionCorrecta = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        peticionIncorrecta = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(campoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 90, 420, 35));

        buscar.setBackground(new java.awt.Color(153, 153, 153));
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-búsqueda-30.png"))); // NOI18N

        javax.swing.GroupLayout buscarLayout = new javax.swing.GroupLayout(buscar);
        buscar.setLayout(buscarLayout);
        buscarLayout.setHorizontalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        buscarLayout.setVerticalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 90, -1, 35));

        tablaBuscar.setModel(new ModeloTablaUsuarios());
        tablaBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBuscarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaBuscar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 470, 200));

        enviarPeticion.setBackground(new java.awt.Color(51, 204, 255));
        enviarPeticion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarPeticionMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enviar petición");

        javax.swing.GroupLayout enviarPeticionLayout = new javax.swing.GroupLayout(enviarPeticion);
        enviarPeticion.setLayout(enviarPeticionLayout);
        enviarPeticionLayout.setHorizontalGroup(
            enviarPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        enviarPeticionLayout.setVerticalGroup(
            enviarPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(enviarPeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 160, 40));

        peticionCorrecta.setForeground(new java.awt.Color(0, 255, 51));
        peticionCorrecta.setText("Petición de amistad enviada correctamente.");
        add(peticionCorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 260, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("BUSCAR USUARIOS");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 490, 30));

        peticionIncorrecta.setForeground(new java.awt.Color(255, 51, 0));
        peticionIncorrecta.setText("Fallo al enviar la petición de amistad");
        add(peticionIncorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        // TODO add your handling code here:
        this.peticionCorrecta.setVisible(false);
        this.peticionIncorrecta.setVisible(false);
        ModeloTablaUsuarios tabla = new ModeloTablaUsuarios();
        tablaBuscar.setModel(tabla);
        tabla.setFilas(new ArrayList<String>());
        try{
            if(campoBuscar.getText()==null||campoBuscar.getText().equals("")) campoBuscar.setText("");
            String [] usuarios = parent.getServidor().buscarPersona(usuario,campoBuscar.getText().toLowerCase());
            if(usuarios.length>0){
                tabla = new ModeloTablaUsuarios();
                tablaBuscar.setModel(tabla);
                ArrayList<String> filas = new ArrayList<>(Arrays.asList(usuarios));
                tabla.setFilas(filas);
            }
        }catch(Exception ex){
            System.out.println("Fallo buscando usuarios (buscarMouseClicked)");
        }
    }//GEN-LAST:event_buscarMouseClicked

    private void tablaBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBuscarMouseClicked
        // TODO add your handling code here:
        this.peticionCorrecta.setVisible(false);
        this.peticionIncorrecta.setVisible(false);
    }//GEN-LAST:event_tablaBuscarMouseClicked

    private void enviarPeticionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarPeticionMouseClicked
        // TODO add your handling code here:
        ModeloTablaUsuarios m = (ModeloTablaUsuarios) tablaBuscar.getModel();
        String receptor = m.getFila(tablaBuscar.getSelectedRow());
        try{
            if(parent.getServidor().enviarPeticion(parent.getClienteIm().getNombre(), receptor)){
                this.peticionCorrecta.setVisible(true);
                this.peticionIncorrecta.setVisible(false);
            }else{
                this.peticionCorrecta.setVisible(false);
                this.peticionIncorrecta.setVisible(true);
            }
        }catch(Exception ex){
            System.out.println("Fallo enviando peticion (enviarPeticionMouseClicked");
        }

    }//GEN-LAST:event_enviarPeticionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JPanel enviarPeticion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel peticionCorrecta;
    private javax.swing.JLabel peticionIncorrecta;
    private javax.swing.JTable tablaBuscar;
    // End of variables declaration//GEN-END:variables
}
