/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peer2peer;

import java.util.ArrayList;

/**
 *
 * @author carlo
 */
public class panelPeticiones extends javax.swing.JPanel {
    GUIClient parent;
    ArrayList<String> peticiones;
    /**
     * Creates new form panelPeticiones
     */
    public panelPeticiones(GUIClient parent, ArrayList<String> peticiones) {
        initComponents();
        this.parent = parent;
        this.peticiones = peticiones;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rechazarPeticion = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        aceptarPeticion = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPeticiones = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rechazarPeticion.setBackground(new java.awt.Color(51, 204, 255));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("RECHAZAR PETICION");

        javax.swing.GroupLayout rechazarPeticionLayout = new javax.swing.GroupLayout(rechazarPeticion);
        rechazarPeticion.setLayout(rechazarPeticionLayout);
        rechazarPeticionLayout.setHorizontalGroup(
            rechazarPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(rechazarPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rechazarPeticionLayout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        rechazarPeticionLayout.setVerticalGroup(
            rechazarPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(rechazarPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rechazarPeticionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(rechazarPeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 160, 40));

        aceptarPeticion.setBackground(new java.awt.Color(51, 204, 255));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ACEPTAR PETICION");

        javax.swing.GroupLayout aceptarPeticionLayout = new javax.swing.GroupLayout(aceptarPeticion);
        aceptarPeticion.setLayout(aceptarPeticionLayout);
        aceptarPeticionLayout.setHorizontalGroup(
            aceptarPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(aceptarPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aceptarPeticionLayout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        aceptarPeticionLayout.setVerticalGroup(
            aceptarPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(aceptarPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aceptarPeticionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(aceptarPeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 160, 40));

        tablaPeticiones.setModel(new ModeloTablaUsuarios());
        jScrollPane2.setViewportView(tablaPeticiones);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 140));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PETICIONES DE AMISTAD PENDIENTES");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 460, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aceptarPeticion;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel rechazarPeticion;
    private javax.swing.JTable tablaPeticiones;
    // End of variables declaration//GEN-END:variables
}
