/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peer2peer;

import java.util.*;

/**
 *
 * @author carlo
 */
public class panelChats extends javax.swing.JPanel {
    GUIClient parent;
    String chatActivo;
    HashMap<String, ArrayList<Mensaje>> mensajes;
    /**
     * Creates new form panelChats
     */
    public panelChats(GUIClient parent, HashMap<String, ArrayList<Mensaje>> mensajes) {
        initComponents();
        this.parent = parent;
        chatActivo = null;
        this.mensajes = mensajes;
        ModeloTablaUsuarios tabla = new ModeloTablaUsuarios();
        tablaChats.setModel(tabla);
        this.panelConver.setVisible(false);
        try{
            tabla.setFilas(new ArrayList<>(Arrays.asList(parent.getClienteIm().getAmigos())));
        }catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConver = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nombreAmigoChat = new javax.swing.JLabel();
        enLinea = new javax.swing.JLabel();
        desconectado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mensaje0 = new javax.swing.JLabel();
        mensaje9 = new javax.swing.JLabel();
        mensaje8 = new javax.swing.JLabel();
        mensaje7 = new javax.swing.JLabel();
        mensaje6 = new javax.swing.JLabel();
        mensaje5 = new javax.swing.JLabel();
        mensaje4 = new javax.swing.JLabel();
        mensaje3 = new javax.swing.JLabel();
        mensaje2 = new javax.swing.JLabel();
        mensaje1 = new javax.swing.JLabel();
        enviarMensaje = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textoMensaje = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        panelAmigos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaChats = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(680, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelConver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreAmigoChat.setBackground(new java.awt.Color(102, 102, 102));
        nombreAmigoChat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreAmigoChat.setText("NOMBRE DEL AMIGO");
        jPanel1.add(nombreAmigoChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 270, 50));

        enLinea.setText("(EN LÍNEA)");
        jPanel1.add(enLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 70, 50));

        desconectado.setText("DESCONECTADO");
        jPanel1.add(desconectado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, 50));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelConver.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        mensaje0.setBackground(new java.awt.Color(102, 102, 102));
        mensaje0.setText("jLabel1");
        panelConver.add(mensaje0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 365, 420, 35));

        mensaje9.setBackground(new java.awt.Color(102, 102, 102));
        mensaje9.setText("jLabel1");
        panelConver.add(mensaje9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 420, 35));

        mensaje8.setBackground(new java.awt.Color(102, 102, 102));
        mensaje8.setText("jLabel1");
        panelConver.add(mensaje8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 420, 35));

        mensaje7.setBackground(new java.awt.Color(102, 102, 102));
        mensaje7.setText("jLabel1");
        panelConver.add(mensaje7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 420, 35));

        mensaje6.setBackground(new java.awt.Color(102, 102, 102));
        mensaje6.setText("jLabel1");
        panelConver.add(mensaje6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 420, 35));

        mensaje5.setBackground(new java.awt.Color(102, 102, 102));
        mensaje5.setText("jLabel1");
        panelConver.add(mensaje5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 420, 35));

        mensaje4.setBackground(new java.awt.Color(102, 102, 102));
        mensaje4.setText("jLabel1");
        panelConver.add(mensaje4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, 420, 35));

        mensaje3.setBackground(new java.awt.Color(102, 102, 102));
        mensaje3.setText("jLabel1");
        panelConver.add(mensaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 420, 35));

        mensaje2.setBackground(new java.awt.Color(102, 102, 102));
        mensaje2.setText("jLabel1");
        panelConver.add(mensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 295, 420, 35));

        mensaje1.setBackground(new java.awt.Color(102, 102, 102));
        mensaje1.setText("jLabel1");
        panelConver.add(mensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 420, 35));

        enviarMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarMensajeMouseClicked(evt);
            }
        });
        enviarMensaje.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("jLabel4");
        enviarMensaje.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        panelConver.add(enviarMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 40, 40));

        textoMensaje.setText("jTextField1");
        panelConver.add(textoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 400, 40));
        panelConver.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 410, -1));

        add(panelConver, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 440, 450));

        panelAmigos.setBackground(new java.awt.Color(153, 153, 153));
        panelAmigos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaChats.setModel(new ModeloTablaUsuarios());
        tablaChats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaChatsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaChats);

        panelAmigos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 400));

        add(panelAmigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaChatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaChatsMouseClicked
        // TODO add your handling code here:
        ModeloTablaUsuarios m = (ModeloTablaUsuarios) tablaChats.getModel();
        this.panelConver.setVisible(true);
        try{
            String receptor = m.getFila(tablaChats.getSelectedRow());
            nombreAmigoChat.setText(receptor);
            if(parent.getClienteIm().getAmigosConectados().get(receptor)==null){
                enLinea.setVisible(false);
                desconectado.setVisible(true);
            }
            escribirMensajes(receptor);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_tablaChatsMouseClicked

    private void enviarMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarMensajeMouseClicked
        // TODO add your handling code here:
        //clienteIm.getAmigosConectados().get(receptor).recibirMensaje(mensaje, clienteIm.getNombre());
    }//GEN-LAST:event_enviarMensajeMouseClicked
    public void escribirMensajes(String receptor){
        ArrayList<Mensaje> mensajesChat = mensajes.get(receptor);
            switch(mensajesChat.size()){
                case 10:
                    mensaje0.setText(mensajesChat.get(9).getMensaje());
                    if(mensajesChat.get(9).getEmisor().equals(receptor)){ mensaje0.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje0.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje1.setText(mensajesChat.get(8).getMensaje());
                    if(mensajesChat.get(8).getEmisor().equals(receptor)){ mensaje1.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje1.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje2.setText(mensajesChat.get(7).getMensaje());
                    if(mensajesChat.get(7).getEmisor().equals(receptor)){ mensaje2.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje2.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje3.setText(mensajesChat.get(6).getMensaje());
                    if(mensajesChat.get(6).getEmisor().equals(receptor)){ mensaje3.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje3.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje4.setText(mensajesChat.get(5).getMensaje());
                    if(mensajesChat.get(5).getEmisor().equals(receptor)){ mensaje4.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje4.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje5.setText(mensajesChat.get(4).getMensaje());
                    if(mensajesChat.get(4).getEmisor().equals(receptor)){ mensaje5.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje5.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje6.setText(mensajesChat.get(3).getMensaje());
                    if(mensajesChat.get(3).getEmisor().equals(receptor)){ mensaje6.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje6.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje7.setText(mensajesChat.get(2).getMensaje());
                    if(mensajesChat.get(2).getEmisor().equals(receptor)){ mensaje7.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje7.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje8.setText(mensajesChat.get(1).getMensaje());
                    if(mensajesChat.get(1).getEmisor().equals(receptor)){ mensaje8.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje8.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje9.setText(mensajesChat.get(0).getMensaje());
                    if(mensajesChat.get(0).getEmisor().equals(receptor)){ mensaje9.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje9.setAlignmentX(RIGHT_ALIGNMENT);}
                    break;
                case 9:
                    mensaje0.setText(mensajesChat.get(8).getMensaje());
                    if(mensajesChat.get(8).getEmisor().equals(receptor)){ mensaje0.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje0.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje1.setText(mensajesChat.get(7).getMensaje());
                    if(mensajesChat.get(7).getEmisor().equals(receptor)){ mensaje1.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje1.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje2.setText(mensajesChat.get(6).getMensaje());
                    if(mensajesChat.get(6).getEmisor().equals(receptor)){ mensaje2.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje2.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje3.setText(mensajesChat.get(5).getMensaje());
                    if(mensajesChat.get(5).getEmisor().equals(receptor)){ mensaje3.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje3.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje4.setText(mensajesChat.get(4).getMensaje());
                    if(mensajesChat.get(4).getEmisor().equals(receptor)){ mensaje4.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje4.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje5.setText(mensajesChat.get(3).getMensaje());
                    if(mensajesChat.get(3).getEmisor().equals(receptor)){ mensaje5.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje5.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje6.setText(mensajesChat.get(2).getMensaje());
                    if(mensajesChat.get(2).getEmisor().equals(receptor)){ mensaje6.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje6.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje7.setText(mensajesChat.get(1).getMensaje());
                    if(mensajesChat.get(1).getEmisor().equals(receptor)){ mensaje7.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje7.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje8.setText(mensajesChat.get(0).getMensaje());
                    if(mensajesChat.get(0).getEmisor().equals(receptor)){ mensaje8.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje8.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje9.setText("");
                    break;
                case 8:
                    mensaje0.setText(mensajesChat.get(7).getMensaje());
                    if(mensajesChat.get(7).getEmisor().equals(receptor)){ mensaje0.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje0.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje1.setText(mensajesChat.get(6).getMensaje());
                    if(mensajesChat.get(6).getEmisor().equals(receptor)){ mensaje1.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje1.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje2.setText(mensajesChat.get(5).getMensaje());
                    if(mensajesChat.get(5).getEmisor().equals(receptor)){ mensaje2.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje2.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje3.setText(mensajesChat.get(4).getMensaje());
                    if(mensajesChat.get(4).getEmisor().equals(receptor)){ mensaje3.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje3.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje4.setText(mensajesChat.get(3).getMensaje());
                    if(mensajesChat.get(3).getEmisor().equals(receptor)){ mensaje4.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje4.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje5.setText(mensajesChat.get(2).getMensaje());
                    if(mensajesChat.get(2).getEmisor().equals(receptor)){ mensaje5.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje5.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje6.setText(mensajesChat.get(1).getMensaje());
                    if(mensajesChat.get(1).getEmisor().equals(receptor)){ mensaje6.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje6.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje7.setText(mensajesChat.get(0).getMensaje());
                    if(mensajesChat.get(0).getEmisor().equals(receptor)){ mensaje7.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje7.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje8.setText("");
                    mensaje9.setText("");
                    break;
                case 7:
                    mensaje0.setText(mensajesChat.get(6).getMensaje());
                    if(mensajesChat.get(6).getEmisor().equals(receptor)){ mensaje0.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje0.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje1.setText(mensajesChat.get(5).getMensaje());
                    if(mensajesChat.get(5).getEmisor().equals(receptor)){ mensaje1.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje1.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje2.setText(mensajesChat.get(4).getMensaje());
                    if(mensajesChat.get(4).getEmisor().equals(receptor)){ mensaje2.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje2.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje3.setText(mensajesChat.get(3).getMensaje());
                    if(mensajesChat.get(3).getEmisor().equals(receptor)){ mensaje3.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje3.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje4.setText(mensajesChat.get(2).getMensaje());
                    if(mensajesChat.get(2).getEmisor().equals(receptor)){ mensaje4.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje4.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje5.setText(mensajesChat.get(1).getMensaje());
                    if(mensajesChat.get(1).getEmisor().equals(receptor)){ mensaje5.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje5.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje6.setText(mensajesChat.get(0).getMensaje());
                    if(mensajesChat.get(0).getEmisor().equals(receptor)){ mensaje6.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje6.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje7.setText("");
                    mensaje8.setText("");
                    mensaje9.setText("");
                    break;
                case 6:
                    mensaje0.setText(mensajesChat.get(5).getMensaje());
                    if(mensajesChat.get(5).getEmisor().equals(receptor)){ mensaje0.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje0.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje1.setText(mensajesChat.get(4).getMensaje());
                    if(mensajesChat.get(4).getEmisor().equals(receptor)){ mensaje1.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje1.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje2.setText(mensajesChat.get(3).getMensaje());
                    if(mensajesChat.get(3).getEmisor().equals(receptor)){ mensaje2.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje2.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje3.setText(mensajesChat.get(2).getMensaje());
                    if(mensajesChat.get(2).getEmisor().equals(receptor)){ mensaje3.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje3.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje4.setText(mensajesChat.get(1).getMensaje());
                    if(mensajesChat.get(1).getEmisor().equals(receptor)){ mensaje4.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje4.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje5.setText(mensajesChat.get(0).getMensaje());
                    if(mensajesChat.get(0).getEmisor().equals(receptor)){ mensaje5.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje5.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje6.setText("");
                    mensaje7.setText("");
                    mensaje8.setText("");
                    mensaje9.setText("");
                    break;
                case 5:
                    mensaje0.setText(mensajesChat.get(4).getMensaje());
                    if(mensajesChat.get(4).getEmisor().equals(receptor)){ mensaje0.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje0.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje1.setText(mensajesChat.get(3).getMensaje());
                    if(mensajesChat.get(3).getEmisor().equals(receptor)){ mensaje1.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje1.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje2.setText(mensajesChat.get(2).getMensaje());
                    if(mensajesChat.get(2).getEmisor().equals(receptor)){ mensaje2.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje2.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje3.setText(mensajesChat.get(1).getMensaje());
                    if(mensajesChat.get(1).getEmisor().equals(receptor)){ mensaje3.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje3.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje4.setText(mensajesChat.get(0).getMensaje());
                    if(mensajesChat.get(0).getEmisor().equals(receptor)){ mensaje4.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje4.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje5.setText("");
                    mensaje6.setText("");
                    mensaje7.setText("");
                    mensaje8.setText("");
                    mensaje9.setText("");
                    break;
                case 4:
                    mensaje0.setText(mensajesChat.get(3).getMensaje());
                    if(mensajesChat.get(3).getEmisor().equals(receptor)){ mensaje0.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje0.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje1.setText(mensajesChat.get(2).getMensaje());
                    if(mensajesChat.get(2).getEmisor().equals(receptor)){ mensaje1.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje1.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje2.setText(mensajesChat.get(1).getMensaje());
                    if(mensajesChat.get(1).getEmisor().equals(receptor)){ mensaje2.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje2.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje3.setText(mensajesChat.get(0).getMensaje());
                    if(mensajesChat.get(0).getEmisor().equals(receptor)){ mensaje3.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje3.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje4.setText("");
                    mensaje5.setText("");
                    mensaje6.setText("");
                    mensaje7.setText("");
                    mensaje8.setText("");
                    mensaje9.setText("");
                    break;
                case 3:
                    mensaje0.setText(mensajesChat.get(2).getMensaje());
                    if(mensajesChat.get(2).getEmisor().equals(receptor)){ mensaje0.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje0.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje1.setText(mensajesChat.get(1).getMensaje());
                    if(mensajesChat.get(1).getEmisor().equals(receptor)){ mensaje1.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje1.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje2.setText(mensajesChat.get(0).getMensaje());
                    if(mensajesChat.get(0).getEmisor().equals(receptor)){ mensaje2.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje2.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje3.setText("");
                    mensaje4.setText("");
                    mensaje5.setText("");
                    mensaje6.setText("");
                    mensaje7.setText("");
                    mensaje8.setText("");
                    mensaje9.setText("");
                    break;
                case 2:
                    mensaje0.setText(mensajesChat.get(1).getMensaje());
                    if(mensajesChat.get(1).getEmisor().equals(receptor)){ mensaje0.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje0.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje1.setText(mensajesChat.get(0).getMensaje());
                    if(mensajesChat.get(0).getEmisor().equals(receptor)){ mensaje1.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje1.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje2.setText("");
                    mensaje3.setText("");
                    mensaje4.setText("");
                    mensaje5.setText("");
                    mensaje6.setText("");
                    mensaje7.setText("");
                    mensaje8.setText("");
                    mensaje9.setText("");
                    break;
                case 1:
                    mensaje0.setText(mensajesChat.get(0).getMensaje());
                    if(mensajesChat.get(0).getEmisor().equals(receptor)){ mensaje0.setAlignmentX(LEFT_ALIGNMENT);
                    }else{mensaje0.setAlignmentX(RIGHT_ALIGNMENT);}
                    
                    mensaje1.setText("");
                    mensaje2.setText("");
                    mensaje3.setText("");
                    mensaje4.setText("");
                    mensaje5.setText("");
                    mensaje6.setText("");
                    mensaje7.setText("");
                    mensaje8.setText("");
                    mensaje9.setText("");
                    break;
                case 0:
                    mensaje0.setText("");
                    mensaje1.setText("");
                    mensaje2.setText("");
                    mensaje3.setText("");
                    mensaje4.setText("");
                    mensaje5.setText("");
                    mensaje6.setText("");
                    mensaje7.setText("");
                    mensaje8.setText("");
                    mensaje9.setText("");
                    break;
                    
                    
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel desconectado;
    private javax.swing.JLabel enLinea;
    private javax.swing.JPanel enviarMensaje;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensaje0;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JLabel mensaje3;
    private javax.swing.JLabel mensaje4;
    private javax.swing.JLabel mensaje5;
    private javax.swing.JLabel mensaje6;
    private javax.swing.JLabel mensaje7;
    private javax.swing.JLabel mensaje8;
    private javax.swing.JLabel mensaje9;
    private javax.swing.JLabel nombreAmigoChat;
    private javax.swing.JPanel panelAmigos;
    private javax.swing.JPanel panelConver;
    private javax.swing.JTable tablaChats;
    private javax.swing.JTextField textoMensaje;
    // End of variables declaration//GEN-END:variables
}
