package peer2peer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author raquel
 */
public class panelPerfil extends javax.swing.JPanel {

    GUIClient parent;
    /**
     * Creates new form panelPerfil
     */
    public panelPerfil(GUIClient parent, String nombre) {
        initComponents();
        this.parent = parent;
        this.nombreUsuarioText.setText(nombre);
        this.mensajePsswActualizada.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombreUsuarioText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        botonEliminarCuenta = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        botonActualizarPassword = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mensajePsswActualizada = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(680, 450));
        setMinimumSize(new java.awt.Dimension(680, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Contraseña");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 200, 29));

        jLabel7.setText("Nombre usuario");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 180, 29));

        nombreUsuarioText.setText("jTextField1");
        nombreUsuarioText.setEnabled(false);
        add(nombreUsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 320, 30));

        passwordText.setText("jPasswordField1");
        add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 320, 30));

        botonEliminarCuenta.setBackground(new java.awt.Color(23, 118, 137));
        botonEliminarCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEliminarCuentaMouseClicked(evt);
            }
        });
        botonEliminarCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Eliminar cuenta");
        botonEliminarCuenta.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 136, 40));

        add(botonEliminarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 190, 40));

        botonActualizarPassword.setBackground(new java.awt.Color(23, 118, 137));
        botonActualizarPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonActualizarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonActualizarPasswordMouseClicked(evt);
            }
        });
        botonActualizarPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Actualizar contraseña");
        botonActualizarPassword.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 40));

        add(botonActualizarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 200, 40));

        jPanel1.setBackground(new java.awt.Color(234, 168, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Perfil usuario");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 460, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 720, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-editar-usuario-masculino-100(1).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        mensajePsswActualizada.setForeground(new java.awt.Color(1, 103, 21));
        mensajePsswActualizada.setText("la contraseña se ha actualizado con exito");
        add(mensajePsswActualizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 380, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarCuentaMouseClicked
        // TODO add your handling code here:
        parent.eliminarCuenta();
    }//GEN-LAST:event_botonEliminarCuentaMouseClicked

    private void botonActualizarPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarPasswordMouseClicked
        // TODO add your handling code here:
       if( parent.actualizarPassword(this.passwordText.getText())){
           this.mensajePsswActualizada.setVisible(true);
       }
    }//GEN-LAST:event_botonActualizarPasswordMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonActualizarPassword;
    private javax.swing.JPanel botonEliminarCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensajePsswActualizada;
    private javax.swing.JTextField nombreUsuarioText;
    private javax.swing.JPasswordField passwordText;
    // End of variables declaration//GEN-END:variables
}
